### ISSUE TITLE
real world example

### ISSUE THREAD

**Issue by ezekielchentnik** [rackt/react-router-tutorial#1]
in response to:  '1. an app that isn't completely pointless'

what would be a good real world example?  ... I've got a team working on a 'real', real world app... involving complex/deep navigation - but doubt its validity in helping others (we're solving horrible, horrible information architecture, react router to the rescue!)

I am curious as to what the world actually wants?

some ideas:
1. blog, front to back (categories, sections, posts, comments, etc.)
2. multi-step form/workflow
3. mobile app
4. ???

**Comment by revolunet** [comment]
data fetching

**Comment by ryanflorence** [comment]
I've got an app that's 80% done that was going to be the subject matter of this tutorial, but it was time to ship 2.0 and we needed a tutorial, so I whipped this together yesterday instead. It'll come, eventually. Maybe it won't be a tutorial, but the code for a real app will be on github.
