### ISSUE TITLE
Issue in lesson 06

### ISSUE THREAD

**Issue by ttyao** [rackt/react-router-tutorial#10]
There is an extra line of `<IndexRoute component={Home}/>` in lesson 6, which prevent the code from compiling. You haven't talked about IndexRoute there yet. :)

**Comment by ttyao** [comment]
I tried to submit a PR to fix it but no permission

**Comment by fhelwanger** [comment]
There's already a PR for this: #6

**Comment by ttyao** [comment]
cool
